### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by pramithready** [gingersmith4/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
  - The link to the test file is broken and shows a 404 error page
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
  - The link to the test file is broken and shows a 404 error page
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
  - The link to the test file is broken and shows a 404 error page
- [x] Symptom shown as command + output for bug/input 3
  - We also want to see the actual command that produced this terminal output, so make sure the screenshot includes both
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Great work!

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by gingersmith4** [comment]
I added links to the test files that work, they're different now because in lab we were using someone else's tests which were different but I have a screenshot of the file that caused the error and the link now works, the file has just been changed.

**Comment by pramithready** [comment]
Looks good, your score has been updated!
